### ISSUE TITLE
Organize DMT documents on Google Drive

### ISSUE THREAD

**Issue by ngalbraith** [oceansites/dmt#14]
Our 3 current draft documents are now in DMT Business / DMT Documents / WorkingDocuments. I think this has been shared with all who need to edit it, but I may have missed some.

**Comment by dpsnowden** [comment]
Moving an email thread here for group discussion, resolution etc.

From Nan
To DMT
2016-06-07

...
I'm still having a little trouble finding/using the google drive versions of the
DMT documents, and just moved some from the main 'DMT documents' folder
into the 'working documents' sub-folder. There seem to be a lot of duplicates
in that folder, and I'm not sure why that's happening - is it something in my drive
settings, that creates copies instead of editing in place?

Also, it seems like our very long filenames don't show up correctly in the browser,
so maybe we should re-name some of these, at least while they're under review or
being drafted. Does anyone object to calling e.g. the  'OceanSITES Data Format Reference
Manual' something like 'format manual' so different versions are clear in the list
of documents? There's one version of this called 'short', which is meant to have ONLY
content that's relevant to the format spec, and another called v 1.3.c, which is just a
slightly updated version of the old (long) document.

Also, the formatting in the old Word doc versions was a little ... precise,
and doesn't seem to be handled very well in google docs. It's not clear to me
whether we want to stick with Word, or open these in  google docs - if the
latter, we may need to make some changes to the formatting.
...

**Comment by dpsnowden** [comment]
We need to devise a GDrive folder structure.  A draft version control strategy is described in #4 

OceanSITES
   +--EC
   +--DMT
       +--Docs
       +--

**Comment by ngalbraith** [comment]
I think I replied to this via email,  I'm adding my proposal here.

If the approved docs are in a single 'directory' we can make them public and keep the working versions private more easily. The public folder would have PDFs and MSWord versions of the DMT dcuments, with the working directory containing google docs files. (There is an issue with our MSWord format, which is an IFREMER design that does not translate to gdocs very well).

Having SC and DMT docs mixed together is also an issue because of the way we work; the SC has to approve DMT documents. They also have a bit of a different way of organizing their docs, without the 'audience focus' we're trying to use. I'd like to be able to point to the DMT's 3 documents as required reading for DACs, and would not want to overload PIs with the details behind our format and data distribution system.

I'd prefer:
+ OceanSITES
    +-- DMT 
          +--Working Documents
                +--Data Users Guide
                +--Data Providers Guide
                +--Data Format Reference
         +--Approved Documents
                +--Data Users Guide
                +--Data Providers Guide
                +--Data Format Reference

**Comment by dpsnowden** [comment]
We discovered that @champikagallage has to share the tope level "OceanSITES" folder with everyone in order for them to be able to see the driectory tree we created.  Previously only link sharing was enabled so the team could see the docs only if the link was sent to them.

**Comment by dpsnowden** [comment]
At this point we opted for a the solution described [here](https://github.com/oceansites/dmt/issues/14#issuecomment-224450939).  This is a decision we made on 2016-08-01 but if it proves unwieldy we can revisit.  The directory structure has been implemented on Google DRive and if you require access contact @cgallage
