### ISSUE TITLE
Triton data : work with jamstec to initiate the dataflow to GDAC

### ISSUE THREAD

**Issue by dpsnowden** [oceansites/dmt#45]
From Mantis

**Comment by tcarval** [comment]
Corentin is contacting Paul and Dai to setup the link TRITON - PMEL - OceanSITES.

**Paul Freitag agreement to provide TRITON data through PMEL, 22/03/2016**
Hi Paul,
Thank you very much for this proposal.
I confirm that this is an excellent option for Ifremer users (such as Copernicus marine service and Mercator).
It is consistent with PIRATA and RAMA.

As you mention, OceanSITES data system promotes a distribution per deployment with metadata on instruments, calibrations used for each deployment.
This distribution may be a next step from JAMSTEC.

However, a hourly time-series of each TRITON moorings in a single OceanSITES NetCDF file will remain very valuable data for users.
Best regards,

Thierry

De : Paul Freitag - NOAA Affiliate [mailto:paul.freitag@noaa.gov]
Envoyé : lundi 21 mars 2016 21:59
À : Thierry Carval Thierry.Carval@ifremer.fr
Cc : andouk andouk@jamstec.go.jp; Corentin.Guyot@ifremer.fr; Derrick Snowden Derrick.Snowden@noaa.gov; uekii@jamstec.go.jp; Jing Zhou Jing.Zhou@noaa.gov; Dai Mcclurg - NOAA Affiliate dai.c.mcclurg@noaa.gov
Objet : Re: OceanSITES Pirata and Rama: 10 minutes sampling instead of daily averages

Hi Thierry,
Sorry for the delay in response. We presently don't have TRITON data in OceanSITES format. We've discussed this among our group and believe we could provide higher resolution TRITON data in a fashion similar to what we provide for PIRATA and RAMA, i.e., in the OS template, but with all deployments for a given site in a single file. We could do this for TRITON moorings in both the Indian and Pacific basins. We note though that the highest resolution TRITON data we have are at hourly intervals. While TRITON moorings generate data at 10-min intervals its our understanding that JAMSTEC considers the hourly time series as their highest quality-controlled data set, If this would satisfy your request for high resolution TRITON data we can format what we have for OceanSITES usage.
Regards,
Paul

**Comment by tcarval** [comment]
Done by way of PMEL which deliver Triton data along Pirata and Rama.
Derrick, can you close that issue ?
